In [2]:
import pandas as pd
df = pd.read_csv("Telco-Customer-Churn.csv")
df.head()


customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [4]:
# ok so 11 missing values in TotalCharges so we wil fill them with median
df['TotalCharges']=df['TotalCharges'].fillna(df['TotalCharges'].median())
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
# now will convert traget variable(churn)
df['Churn']=df['Churn'].map({'Yes':1,'No':0})
df['Churn'].value_counts()
# so the outputs shows that we have imbalanced classes

Churn
0    5174
1    1869
Name: count, dtype: int64

In [6]:
# as customer id is unique, no predictive power and can cause of so we will drop it
df=df.drop('customerID',axis=1)
# we add inplace=True to make the changes in the same dataframe

In [7]:
# ok lets separete cat and num vals
categorical_cols = df.select_dtypes(include=['object']).columns
numerical_cols = df.select_dtypes(exclude=['object']).columns

print("Categorical columns:", categorical_cols)
print("Numerical columns:", numerical_cols) 

# we have 19 categorical columns and 4 numerical columns

Categorical columns: Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')
Numerical columns: Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn'], dtype='object')


In [8]:
# now will encode cat cols-1 hot encode

df_enc = pd.get_dummies(df, drop_first=True)
print(df_enc)
print(df.shape)
print(df_enc.shape)

# we use drop_first=True to avoid any dummy var , hence we will avoid multicollinearity

      SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Churn  gender_Male  \
0                 0       1           29.85         29.85      0        False   
1                 0      34           56.95       1889.50      0         True   
2                 0       2           53.85        108.15      1         True   
3                 0      45           42.30       1840.75      0         True   
4                 0       2           70.70        151.65      1        False   
...             ...     ...             ...           ...    ...          ...   
7038              0      24           84.80       1990.50      0         True   
7039              0      72          103.20       7362.90      0        False   
7040              0      11           29.60        346.45      0        False   
7041              1       4           74.40        306.60      1         True   
7042              0      66          105.65       6844.50      0         True   

      Partner_Yes  Dependen

In [9]:
df_enc.info()
df_enc.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   SeniorCitizen                          7043 non-null   int64  
 1   tenure                                 7043 non-null   int64  
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7043 non-null   float64
 4   Churn                                  7043 non-null   int64  
 5   gender_Male                            7043 non-null   bool   
 6   Partner_Yes                            7043 non-null   bool   
 7   Dependents_Yes                         7043 non-null   bool   
 8   PhoneService_Yes                       7043 non-null   bool   
 9   MultipleLines_No phone service         7043 non-null   bool   
 10  MultipleLines_Yes                      7043 non-null   bool   
 11  Inte

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Churn  gender_Male  \
0              0       1           29.85         29.85      0        False   
1              0      34           56.95       1889.50      0         True   
2              0       2           53.85        108.15      1         True   
3              0      45           42.30       1840.75      0         True   
4              0       2           70.70        151.65      1        False   

   Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0         True           False             False   
1        False           False              True   
2        False           False              True   
3        False           False             False   
4        False           False              True   

   MultipleLines_No phone service  ...  StreamingTV_No internet service  \
0                            True  ...                            False   
1                           False  ...                            False   
2                           False  ...                            False   
3                            True  ...                            False   
4                           False  ...                            False   

   StreamingTV_Yes  StreamingMovies_No internet service  StreamingMovies_Yes  \
0            False                                False                False   
1            False                                False                False   
2            False                                False                False   
3            False                                False                False   
4            False                                False                False   

   Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0              False              False                  True   
1               True              False                 False   
2              False              False                  True   
3               True              False                 False   
4              False              False                  True   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True   
1                                  False                           False   
2                                  False                           False   
3                                  False                           False   
4                                  False                            True   

   PaymentMethod_Mailed check  
0                       False  
1                        True  
2                        True  
3                       False  
4                       False  

[5 rows x 31 columns]

In [10]:
print(df_enc.isnull().sum().sum())
df_enc.select_dtypes(include='object').shape
# so no more categorical cols and null values


0


(7043, 0)

In [11]:
X = df_enc.drop('Churn', axis=1)
y = df_enc['Churn']

num_features=[
    'tenure',
    'MonthlyCharges',
    'TotalCharges'
]
# from this will identify num features 
X[num_features].describe()


tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7043.000000
mean     32.371149       64.761692   2281.916928
std      24.559481       30.090047   2265.270398
min       0.000000       18.250000     18.800000
25%       9.000000       35.500000    402.225000
50%      29.000000       70.350000   1397.475000
75%      55.000000       89.850000   3786.600000
max      72.000000      118.750000   8684.800000

In [12]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [13]:

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_scaled=X.copy()
X_scaled[num_features]=scaler.fit_transform(X[num_features])
# we scaled only num features because cat features are already encoded

X_scaled[num_features].describe()



tenure  MonthlyCharges  TotalCharges
count  7.043000e+03    7.043000e+03  7.043000e+03
mean  -2.421273e-17   -6.406285e-17 -1.488074e-17
std    1.000071e+00    1.000071e+00  1.000071e+00
min   -1.318165e+00   -1.545860e+00 -9.991203e-01
25%   -9.516817e-01   -9.725399e-01 -8.298459e-01
50%   -1.372744e-01    1.857327e-01 -3.904632e-01
75%    9.214551e-01    8.338335e-01  6.642871e-01
max    1.613701e+00    1.794352e+00  2.826743e+00

In [14]:
print(X[num_features])
print(X_scaled[num_features])


      tenure  MonthlyCharges  TotalCharges
0          1           29.85         29.85
1         34           56.95       1889.50
2          2           53.85        108.15
3         45           42.30       1840.75
4          2           70.70        151.65
...      ...             ...           ...
7038      24           84.80       1990.50
7039      72          103.20       7362.90
7040      11           29.60        346.45
7041       4           74.40        306.60
7042      66          105.65       6844.50

[7043 rows x 3 columns]
        tenure  MonthlyCharges  TotalCharges
0    -1.277445       -1.160323     -0.994242
1     0.066327       -0.259629     -0.173244
2    -1.236724       -0.362660     -0.959674
3     0.514251       -0.746535     -0.194766
4    -1.236724        0.197365     -0.940470
...        ...             ...           ...
7038 -0.340876        0.665992     -0.128655
7039  1.613701        1.277533      2.243151
7040 -0.870241       -1.168632     -0.854469
7041 -1.1

In [15]:

print(X_scaled.shape)
print(X.shape)


(7043, 30)
(7043, 30)


Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42,stratify=y) 

#lets check shapes of x train and test sets
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

# lets verify churn ratio remains same in train and test sets
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

# so churn ratio is same in both so they are balanced, and stratifed split worked well 

(5634, 30) (1409, 30) (5634,) (1409,)
Churn
0    0.734647
1    0.265353
Name: proportion, dtype: float64
Churn
0    0.734564
1    0.265436
Name: proportion, dtype: float64


Logistic Regression with Balanced Weight Classes

In [17]:
from sklearn.linear_model import LogisticRegression

# lets use log r with balanced class weights
LogR=LogisticRegression(max_iter=1000,class_weight='balanced',random_state=42)

LogR.fit(X_train,y_train)
y_pred=LogR.predict(X_test)
y_pred_prob=LogR.predict_proba(X_test)[:,1]  # probability estimates for positive class

In [18]:
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report, recall_score, precision_score

'''accuracy_score(y_test,y_pred)
roc_auc_score(y_test,y_pred_prob)
classification_report(y_test,y_pred)
confusion_matrix(y_test,y_pred)
recall_score(y_test,y_pred)
precision_score(y_test,y_pred)'''

print("Accuracy:", accuracy_score(y_test,y_pred))
print("ROC AUC Score:", roc_auc_score(y_test,y_pred_prob))  
print("Classification Report:\n", classification_report(y_test,y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred))
print("Recall:", recall_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))

# model is predicting on mostly the majority class (No Churn) due to class imbalance hence auccuracy looks misleading highlyffffff




Accuracy: 0.7388218594748048
ROC AUC Score: 0.8417318969748636
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.78      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

Confusion Matrix:
 [[748 287]
 [ 81 293]]
Recall: 0.7834224598930482
Precision: 0.5051724137931034


Random Forest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

rf= RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    max_depth=10,
    min_samples_split=10
)

rf.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=10, random_state=42)

In [20]:
rf_y_pred=rf.predict(X_test)
rf_y_pred_prob=rf.predict_proba(X_test)[:,1]

In [21]:
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score, confusion_matrix, recall_score

print("Accuracy:", accuracy_score(y_test,rf_y_pred))
print("ROC AUC Score:", roc_auc_score(y_test,rf_y_pred_prob))
print("Classification Report:\n", classification_report(y_test,rf_y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test,rf_y_pred))
print("Recall:", recall_score(y_test,rf_y_pred))


Accuracy: 0.7650816181689141
ROC AUC Score: 0.842275698158051
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.77      0.83      1035
           1       0.54      0.74      0.63       374

    accuracy                           0.77      1409
   macro avg       0.72      0.76      0.73      1409
weighted avg       0.80      0.77      0.78      1409

Confusion Matrix:
 [[800 235]
 [ 96 278]]
Recall: 0.7433155080213903


In [22]:
import pandas as pd
feature_importances=pd.Series(rf.feature_importances_,index=X_train.columns).sort_values(ascending=False)
feature_importances.head(10)

tenure                                  0.174934
TotalCharges                            0.139192
Contract_Two year                       0.106338
MonthlyCharges                          0.103020
InternetService_Fiber optic             0.070595
PaymentMethod_Electronic check          0.050967
Contract_One year                       0.042941
OnlineSecurity_Yes                      0.039387
TechSupport_Yes                         0.025534
DeviceProtection_No internet service    0.020766
dtype: float64

XGBoost

In [23]:
%pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [24]:
from xgboost import XGBClassifier

xgb=XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight= (len(y_train[y_train==0]) / len(y_train[y_train==1])),
    eval_metric='logloss',
    random_state=42
)

xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [25]:
y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:,1]


In [27]:
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score, confusion_matrix, recall_score

print("Accuracy:", accuracy_score(y_test,y_pred_xgb))
print("ROC AUC Score:", roc_auc_score(y_test,y_prob_xgb))
print("Classification Report:\n", classification_report(y_test,y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_xgb))
print("Recall:", recall_score(y_test,y_pred_xgb))

Accuracy: 0.7551454932576295
ROC AUC Score: 0.8427562065669482
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.74      0.82      1035
           1       0.53      0.79      0.63       374

    accuracy                           0.76      1409
   macro avg       0.72      0.77      0.72      1409
weighted avg       0.81      0.76      0.77      1409

Confusion Matrix:
 [[770 265]
 [ 80 294]]
Recall: 0.786096256684492


Threshold tunining

In [34]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# getting the probabilities
y_prob=LogR.predict_proba(X_test)[:,1]

# i can now use y_prob for threshold tuning and lets try different thresholds
thresholds = [0.35, 0.4, 0.5]
for t in thresholds:
    y_pred_thresh=(y_prob>= t).astype(int)
    print(f"Threshold: {t}")
    print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_thresh))
    print("Classification Report:\n", classification_report(y_test,y_pred_thresh))




Threshold: 0.35
Confusion Matrix:
 [[616 419]
 [ 36 338]]
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.60      0.73      1035
           1       0.45      0.90      0.60       374

    accuracy                           0.68      1409
   macro avg       0.70      0.75      0.66      1409
weighted avg       0.81      0.68      0.70      1409

Threshold: 0.4
Confusion Matrix:
 [[664 371]
 [ 50 324]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.64      0.76      1035
           1       0.47      0.87      0.61       374

    accuracy                           0.70      1409
   macro avg       0.70      0.75      0.68      1409
weighted avg       0.81      0.70      0.72      1409

Threshold: 0.5
Confusion Matrix:
 [[748 287]
 [ 81 293]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.72      0.80    